# Generated by Django 5.2.11 on 2026-02-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_category_item_category_unique_category_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_currency',
            field=models.CharField(choices=[('USD', 'US Dollar (USD)'), ('GBP', 'British Pound (GBP)'), ('EUR', 'Euro (EUR)'), ('CAD', 'Canadian Dollar (CAD)'), ('AUD', 'Australian Dollar (AUD)')], default='USD', max_length=3),
        ),
    ]
