# Generated by Django 5.2.11 on 2026-02-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_profile_preferred_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar (USD)'), ('GBP', 'British Pound (GBP)'), ('EUR', 'Euro (EUR)'), ('CAD', 'Canadian Dollar (CAD)'), ('AUD', 'Australian Dollar (AUD)')], default='USD', max_length=3),
        ),
    ]
